### ISSUE TITLE
[0.31.0-RC2] missing BaseSpan

### ISSUE THREAD

**Issue by yurishkuro** [opentracing/opentracing-java#237]
I am trying to upgrade Jaeger client to RC2. It contains an integration test using tchannel that is compiled against 0.30.0. Even though the instrumentation never uses BaseSpan explicitly, if fails at runtime:
```
com.uber.jaeger.crossdock.resources.behavior.http.TraceBehaviorResourceTest > testJoinTraceTChannel[1: sampled(false)] FAILED
    java.lang.NoClassDefFoundError: io/opentracing/BaseSpan
        at com.uber.tchannel.tracing.Tracing.startOutboundSpan(Tracing.java:107)
        at com.uber.tchannel.api.SubChannel.sendOutRequest(SubChannel.java:266)
        at com.uber.tchannel.api.SubChannel.sendRequest(SubChannel.java:245)
        at com.uber.tchannel.api.SubChannel.send(SubChannel.java:192)
        at com.uber.jaeger.crossdock.resources.behavior.TraceBehavior.callDownstreamTChannel(TraceBehavior.java:108)
        at com.uber.jaeger.crossdock.resources.behavior.http.TraceBehaviorResourceTest.testJoinTraceTChannel(TraceBehaviorResourceTest.java:174)

        Caused by:
        java.lang.ClassNotFoundException: io.opentracing.BaseSpan
            at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
            at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
            at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:335)
            at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
            ... 6 more
```

Simply adding the BaseSpan interface back to the module seems to fix this issue (I will post a PR once confirmed).

**Comment by pavolloffay** [comment]
> Simply adding the BaseSpan interface back to the module seems to fix this issue (I will post a PR once confirmed).

I am not sure if adding only `BaseSpan` class is sufficient and generally a good solution. It might be in this case but I don't think it will work in other cases.

**Comment by yurishkuro** [comment]
> I am not sure if adding only BaseSpan class is sufficient and generally a good solution.

what would you suggest instead? My goal was to allow instrumentation compiled against 0.30 but not actually using ActiveSpan features to still work with 0.31.

**Comment by tedsuo** [comment]
@yurishkuro is there a way to verify how big an issue this is? IMHO it is not a big deal to add `BaseSpan`, even as a patch update later, since your solution (https://github.com/opentracing/opentracing-java/pull/238) would not break tracers or instrumentation. But it is "cruft" so if this only helps one or two repos perhaps it isn't worth it? 🤷‍♀️

**Comment by yurishkuro** [comment]
at the moment it's like a circular dependency, an RC branch of Jaeger using 0.31-RC2 had a broken build because integration tests use tchannel which is compiled against 0.30. I was able to get a green build by rolling back tchannel to its pre-0.30 OT version (#313), to my surprise because there was a [change in SAMPLING_PRIORITY flag](https://github.com/uber/tchannel-java/commit/1fbe38a0672e6d2c0b3fb5ee04e503c944b31b01#diff-b84934176d113b477c8752a2dfa22cd0R338).

**Comment by isaachier** [comment]
Took a brief look at the [Java spec](https://docs.oracle.com/javase/specs/jvms/se7/html/jvms-5.html) and it seems this occurs as part of the verification stage, so at least it stops the program from running immediately (not as a result of calling the method later).

**Comment by tedsuo** [comment]
Closing since we chose to release without this change. Please reopen if we want to add this as a patch later.
